title: Caporaso Lab
description: >
  Developing production-quality software products to study our microbial world.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cap-lab.bio" # the base hostname & protocol for your site

author:
  fullname: Cap Lab
  github: caporaso-lab
  youtube: qiime2

# Build settings
markdown: kramdown
